-- À exécuter sur une base Supabase déjà créée avec l'ancien schéma (sans les colonnes chantier).
ALTER TABLE projects ADD COLUMN IF NOT EXISTS site_address TEXT NOT NULL DEFAULT '';
ALTER TABLE projects ADD COLUMN IF NOT EXISTS chantier_type TEXT NOT NULL DEFAULT 'plomberie';
ALTER TABLE projects ADD COLUMN IF NOT EXISTS quote_id BIGINT REFERENCES quotes(id) ON DELETE SET NULL;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS budget_estime DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS heures_prevues DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS heures_passees DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS etape_metier TEXT NOT NULL DEFAULT 'terrassement';
ALTER TABLE projects ADD COLUMN IF NOT EXISTS photo_urls TEXT NOT NULL DEFAULT '[]';
ALTER TABLE projects ADD COLUMN IF NOT EXISTS a_relancer BOOLEAN NOT NULL DEFAULT FALSE;
